version: '3.8'
services:
  api-prod:
    image: node:21-alpine
    container_name: github-stats-api-prod
    command: sh -c "npm install && npm run build && npm run start:prod"
    working_dir: /app
    volumes:
      - ./api:/app
      - ${SSL_DIRECTORY_BIND:-./api}:${SSL_DIRECTORY_BIND:-/app}
    expose:
      - "3000"
    ports:
      - "${API_PORT:-3000}:3000"

  api-dev:
    image: node:21
    container_name: github-stats-api-dev
    command: sh -c "npm install && npm run start:dev"
    working_dir: /app
    volumes:
      - ./api:/app
    expose:
      - "3000"
    ports:
      - "${API_PORT:-3000}:3000"
