FROM node:21-alpine as builder

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

RUN npm run build

FROM node:21-alpine as production

WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY .env /app/.env

RUN npm install --omit=dev

CMD ["node", "dist/main"]
